Weatherman
A-ASAD/Training pull request #2
Opened 2021-07-27 14:06 UTC by A-ASAD

Fetches data from the folder where files are unzipped and displays the yearly reports for now. Other 3 cases are not implemented yet. All supporting modules are implemented. The unzipping part is not added yet.

2021-07-28 02:57 UTC, saadyousafarbi requested changes
I have gone through an overview of the PR and have requested some changes. There are a couple of things you should do in addition to these changes:

- Push the data files as well as part of this PR (it would be easier for me to clone and test out your repo, and check functionality that way),

- Add the `Problem Statement` shared with you to the `README.md` file along with a `Usage` Section where you should add the commands to run to generate the monthly, yearly etc reports,

- Also go through pep8 conventions here https://www.python.org/dev/peps/pep-0008/

If you have any questions, please feel free to ask!

2021-07-28 02:57 UTC, saadyousafarbi commented on calculation_computer.py
> +MonthlyCalculationResults)
```
from calculation_results import (
    YearlyCalculationResults,
    MonthlyCalculationResults,
)
```
would look more cleaner. Please check out pep8 conventions for the best approach!

2021-07-28 02:57 UTC, saadyousafarbi commented on calculation_computer.py
> +    '''
use double quotes here!

2021-07-28 02:57 UTC, saadyousafarbi commented on calculation_computer.py
> +def yearly_calculations(weather_readings):
input names can be better as well. 
`raw_weather_data` could be more representative of what the input actually is!

2021-07-28 02:57 UTC, saadyousafarbi commented on calculation_computer.py
> +    Parameters:
use `Arguments` here instead of `Parameters`. Double in pep8 conventions!

2021-07-28 02:57 UTC, saadyousafarbi commented on calculation_computer.py
> +                                '')
Why are there so many empty `''` Strings being passed to `YearlyCalculationResults` object?

2021-07-28 02:57 UTC, saadyousafarbi commented on calculation_computer.py
> +    '''
Double quotes here!

2021-07-28 02:57 UTC, saadyousafarbi commented on calculation_computer.py
> +        object:
name should be meaningful!

2021-07-28 02:57 UTC, saadyousafarbi commented on calculation_computer.py
> +    result = MonthlyCalculationResults(0, 0, 0)
variable name should be improved. Something like `monthly_weather_report` or `monthly_weather_data`

2021-07-28 02:57 UTC, saadyousafarbi commented on main.py
> +        exit()
use `return` instead of `exit()`

2021-07-28 02:57 UTC, saadyousafarbi commented on parser.py
> +def data_parser(data, name):
`filename` would be more clearer argument name!

2021-07-28 02:57 UTC, saadyousafarbi commented on report_generator.py
> +'''
Double quotes.

2021-07-28 02:57 UTC, saadyousafarbi commented on report_generator.py
> +Methods:
Dont need this here.

2021-07-28 02:57 UTC, saadyousafarbi commented on report_generator.py
> +def print_yearly_report(calculations):
A better name would be `generate_annual_weather_report`

2021-07-28 02:57 UTC, saadyousafarbi commented on report_generator.py
> +
there should be a blank newline at end of file!

2021-07-28 02:57 UTC, saadyousafarbi commented on weather_reading.py
> +    '''
Double quotes!

2021-07-28 02:57 UTC, saadyousafarbi commented on weather_reading.py
> +
Docstring for the file explaining purpose of this file!

2021-07-28 17:37 UTC, A-ASAD commented on calculation_computer.py
> +                                '')
Those arguments hold day and month for the respective values, those will be populated later when temperature and humidity are calculated.

2021-07-28 17:41 UTC, A-ASAD commented
All modules are complete now. I've added usage details in the readme file.

2021-08-03 05:22 UTC, saadyousafarbi commented on README.md
> +`pip install -r requirements.txt`
good work adding the instructions! 👍

2021-08-03 05:40 UTC, saadyousafarbi requested changes
Well done on addressing the feedback from the first review. 👍 

I have added a few more comments, please have a look at these!

2021-08-03 05:40 UTC, saadyousafarbi commented on main.py
> +    if not year.isdecimal():
why are we checking if this is a decimal or not?

2021-08-03 05:40 UTC, saadyousafarbi commented on main.py
> +        if year in file:
why do we have this check here?

2021-08-03 05:40 UTC, saadyousafarbi commented on main.py
> +        print(f'No data found for the year {year}')
you can have a `return` statement at the end of the `if`. That way you can avoid using the `else` statement and just have the print statement at the end!

2021-08-03 05:40 UTC, saadyousafarbi commented on main.py
> +    """
`filenames` is missing from docstring.

2021-08-03 05:40 UTC, saadyousafarbi commented on main.py
> +        if f'{year}_{MONTHS_SHORT[int(month)-1]}' in file:
assign this `f'{year}_{MONTHS_SHORT[int(month)-1]}'` to a variable above.
And name the variable meaningfully, so that it is understandable what the variable holds!

2021-08-03 05:40 UTC, saadyousafarbi commented on main.py
> +    """
`filenames` missing from docstring!

2021-08-03 05:40 UTC, saadyousafarbi commented on main.py
> +        if f'{year}_{MONTHS_SHORT[int(month)-1]}' in file:
as above, move this to a variable.

2021-08-03 05:40 UTC, saadyousafarbi commented on main.py
> +    """
`filename` missing from docstring!

2021-08-03 05:40 UTC, saadyousafarbi commented on main.py
> +def get_monthly_reports_single_bar_chart(path_to_dir, year, month, filenames):
how is this different from the `double_bar_chart` method?

2021-08-03 05:40 UTC, saadyousafarbi commented on main.py
> +def is_valid_month_argument(year_and_month):
`is_valid_date` would be better. Using only `month` is variable name can be misleading as it might be interpreted as only related to month, but in this case, it is related to the full date.

2021-08-03 05:40 UTC, saadyousafarbi commented on report_generator.py
> +            Month for reports are to be generated
incorrent arguments mentioned here. please double check!

2021-08-03 05:40 UTC, saadyousafarbi commented on report_generator.py
> +            Month for reports are to be generated
wrong arguments added to docstring!

2021-08-03 05:40 UTC, saadyousafarbi commented on report_generator.py
> +def generate_monthly_weather_single_bar_chart(raw_monthly_data, year, month):
what is the difference of between this method and the `double_bar_chart` method?

2021-08-03 05:40 UTC, saadyousafarbi commented on weather_reading.py
> +
use `switch case` instead of `if/else` for multiple cases. it is more readable.

2021-08-03 05:40 UTC, saadyousafarbi commented on weatherman_tests.py
> +        from the unzipped directory
add testing instructions to the `README` file as well in a new `Testing` section.

2021-08-03 07:55 UTC, A-ASAD commented on main.py
> +    if not year.isdecimal():
Users can pass any string in the command line, so ensuring that it's a valid number before processing reports.

2021-08-03 07:59 UTC, A-ASAD commented on main.py
> +        if year in file:
filenames is the list of all the data files we have. The file name format is like 'Murree_weather_2004_Aug'. This check here checks if the filename string contains the respective year or not. If yes, we need to process the file otherwise skip that file.

2021-08-03 08:11 UTC, A-ASAD commented on main.py
> +def get_monthly_reports_single_bar_chart(path_to_dir, year, month, filenames):
The double bar chart prints two lines, one for highest temperature and one for lowest.
Single bar chart prints only one line combined for both temperatures.

2021-08-03 09:01 UTC, A-ASAD commented on report_generator.py
> +def generate_monthly_weather_single_bar_chart(raw_monthly_data, year, month):
The double bar chart prints two lines, one for highest temperature and one for lowest.
Single bar chart prints only one line combined for both temperatures.

2021-08-03 09:03 UTC, A-ASAD commented on weather_reading.py
> +
These are actually different values for each if statement. Switch can be used for different cases of a single variable.

2021-08-05 03:46 UTC, saadyousafarbi commented on main.py
> +This is the dirver module
is this a typo?

2021-08-05 03:48 UTC, saadyousafarbi commented on main.py
> +def get_monthly_reports_single_bar_chart(path_to_dir, year, month, filenames):
make these into a single function, and have a new `flag` parameter to the common function that would determine whether to print `single` or `double` bar chart!

2021-08-05 03:49 UTC, saadyousafarbi approved these changes
LGTM! 🎆 
Added some comments!

2021-08-05 03:51 UTC, saadyousafarbi commented
please resolve conflicts, and squash changes in a single commit when merging PR.

2021-08-05 05:46 UTC, A-ASAD commented on main.py
> +This is the dirver module
Yes

2021-08-10 13:16 UTC, merged